routes-to-execute-leaf: judicial-region-type, judicial-base-location_type
route:
  judicial-region-type:
    id: judicial-region-type
    file-name: Locations
    table-name: region_type
    insert-sql:
      sql:INSERT INTO region_type (region_id,region_desc_en,region_desc_cy,mrd_created_time,mrd_updated_time,mrd_deleted_time) 
      VALUES(:#region_id,:#region_desc_en,:#region_desc_cy,:#mrd_created_time,:#mrd_updated_time,:#mrd_deleted_time)
      ON CONFLICT (region_id) DO UPDATE SET region_desc_en = :#region_desc_en,region_desc_cy = :#region_desc_cy,mrd_created_time = :#mrd_created_time,mrd_updated_time = :#mrd_updated_time,mrd_deleted_time = :#mrd_deleted_time?dataSource=dataSource&batch=true
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Locations?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialRegionTypeProcessor
    mapper-class: JudicialRegionTypeRowMapper
    csv-binder-object: JudicialRegionType

  judicial-base-location_type:
    id: judicial-base-location_type
    file-name: BaseLocations
    table-name: base_location_type
    insert-sql:
      sql:INSERT INTO base_location_type (base_location_id,court_name,court_type,circuit,area_of_expertise,mrd_created_time,mrd_updated_time,mrd_deleted_time)
      VALUES(:#base_location_id,:#court_name, :#court_type,:#circuit, :#area_of_expertise, :#mrd_created_time, :#mrd_updated_time, :#mrd_deleted_time)
      ON CONFLICT (base_location_id) DO UPDATE SET court_name = :#court_name,court_type = :#court_type,circuit = :#circuit,area_of_expertise = :#area_of_expertise,mrd_created_time = :#mrd_created_time,mrd_updated_time = :#mrd_updated_time,mrd_deleted_time = :#mrd_deleted_time?dataSource=dataSource&batch=true
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/BaseLocations?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialBaseLocationProcessor
    mapper-class: JudicialBaseLocationRowTypeMapper
    csv-binder-object: JudicialBaseLocationType



