start-leaf-route: direct:leaf
leaf-route-names: judicial-role-type,judicial-contract-type,judicial-region-type,judicial-base-location_type
scheduler-insert-sql: insert into dataload_schedular_audit (scheduler_name,scheduler_start_time,scheduler_end_time,scheduler_status)
  values(?,?,?,?)
scheduler-name: judicial_leaf_scheduler
audit-enable: true
leaf-archival-route: direct:jrdLeafArchival
leaf-archival-file-names: Roles,Contracts,Locations,BaseLocations

leaf-route:
  judicial-role-type:
    id: judicial-role-type
    file-name: Roles
    table-name: judicial_role_type
    insert-sql:
      sql:insert into judicial_role_type (role_id,role_desc_en,role_desc_cy) values(:#role_id,:#role_desc_en,:#role_desc_cy)
      on conflict (role_id) do update set role_desc_en = :#role_desc_en,role_desc_cy = :#role_desc_cy?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Roles?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialUserRoleTypeProcessor
    mapper-class: JudicialRoleTypeRowMapper
    csv-binder-object: JudicialUserRoleType
    route-header : RoleID,Role

  judicial-contract-type:
    id: judicial-contract-type
    file-name: Contracts
    table-name: contract_type
    insert-sql:
      sql:insert into contract_type (contract_type_id,contract_type_desc_en,contract_type_desc_cy) values(:#contract_type_id,:#contract_type_desc_en,:#contract_type_desc_en)
      on conflict (contract_type_id) do update set contract_type_desc_en = :#contract_type_desc_en,contract_type_desc_cy = :#contract_type_desc_cy?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Contracts?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialContractTypeProcessor
    mapper-class: JudicialContractTypeRowMapper
    csv-binder-object: JudicialContractType
    route-header : ContractID,ContractDescription

  judicial-region-type:
    id: judicial-region-type
    file-name: Locations
    table-name: region_type
    insert-sql:
      sql:insert into region_type (region_id,region_desc_en,region_desc_cy) values(:#region_id,:#region_desc_en,:#region_desc_cy)
      on conflict (region_id) do update set region_desc_en = :#region_desc_en,region_desc_cy = :#region_desc_cy?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Locations?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialRegionTypeProcessor
    mapper-class: JudicialRegionTypeRowMapper
    csv-binder-object: JudicialRegionType
    route-header : LocationID,LocationDescription

  judicial-base-location_type:
    id: judicial-base-location_type
    file-name: BaseLocations
    table-name: base_location_type
    insert-sql:
      sql:insert into base_location_type (base_location_id,court_name,court_type,circuit,area_of_expertise) values(:#base_location_id,:#court_name, :#court_type,:#circuit, :#area_of_expertise)
      on conflict (base_location_id) do update set court_name = :#court_name,court_type = :#court_type,circuit = :#circuit,area_of_expertise = :#area_of_expertise?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/BaseLocations?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialBaseLocationProcessor
    mapper-class: JudicialBaseLocationRowTypeMapper
    csv-binder-object: JudicialBaseLocationType
    judicialBaseLocationType : CourtID,Court/Bench,CourtType,Circuit,Area


